//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tutorial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tutorial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jok.Backgammon.Resources.Tutorial", typeof(Tutorial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix - How to play.
        /// </summary>
        public static string A001 {
            get {
                return ResourceManager.GetString("A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Tutorial.
        /// </summary>
        public static string A002 {
            get {
                return ResourceManager.GetString("A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Again?.
        /// </summary>
        public static string A003 {
            get {
                return ResourceManager.GetString("A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string A004 {
            get {
                return ResourceManager.GetString("A004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string A005 {
            get {
                return ResourceManager.GetString("A005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A006 {
            get {
                return ResourceManager.GetString("A006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A007 {
            get {
                return ResourceManager.GetString("A007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A008 {
            get {
                return ResourceManager.GetString("A008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A009 {
            get {
                return ResourceManager.GetString("A009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello. Welcome to the game - Rowena.
        /// </summary>
        public static string A010 {
            get {
                return ResourceManager.GetString("A010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is based on backgammon rules, with a little changes, which makes game more amazing.
        /// </summary>
        public static string A011 {
            get {
                return ResourceManager.GetString("A011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player uses three dices and there are multiple possibilities of pairs.
        /// </summary>
        public static string A012 {
            get {
                return ResourceManager.GetString("A012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When player has two pairs, he must play three times that dice.
        /// </summary>
        public static string A013 {
            get {
                return ResourceManager.GetString("A013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when there are three pairs, player must play six time that dice.
        /// </summary>
        public static string A0131 {
            get {
                return ResourceManager.GetString("A0131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board is splitted into four parts, each part has eight possible moves.
        /// </summary>
        public static string A014 {
            get {
                return ResourceManager.GetString("A014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can move checkers by dragging them and placing in green lighted places.
        /// </summary>
        public static string A015 {
            get {
                return ResourceManager.GetString("A015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or just click checker and you will see all possible moves.
        /// </summary>
        public static string A016 {
            get {
                return ResourceManager.GetString("A016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun dude!.
        /// </summary>
        public static string A017 {
            get {
                return ResourceManager.GetString("A017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A018 {
            get {
                return ResourceManager.GetString("A018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A019 {
            get {
                return ResourceManager.GetString("A019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A020 {
            get {
                return ResourceManager.GetString("A020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A0201 {
            get {
                return ResourceManager.GetString("A0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A021 {
            get {
                return ResourceManager.GetString("A021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A022 {
            get {
                return ResourceManager.GetString("A022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A023 {
            get {
                return ResourceManager.GetString("A023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A024 {
            get {
                return ResourceManager.GetString("A024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A025 {
            get {
                return ResourceManager.GetString("A025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A0251 {
            get {
                return ResourceManager.GetString("A0251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A026 {
            get {
                return ResourceManager.GetString("A026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A027 {
            get {
                return ResourceManager.GetString("A027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A028 {
            get {
                return ResourceManager.GetString("A028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A029 {
            get {
                return ResourceManager.GetString("A029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A030 {
            get {
                return ResourceManager.GetString("A030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A031 {
            get {
                return ResourceManager.GetString("A031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A032 {
            get {
                return ResourceManager.GetString("A032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A033 {
            get {
                return ResourceManager.GetString("A033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A034 {
            get {
                return ResourceManager.GetString("A034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A035 {
            get {
                return ResourceManager.GetString("A035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A036 {
            get {
                return ResourceManager.GetString("A036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A037 {
            get {
                return ResourceManager.GetString("A037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A038 {
            get {
                return ResourceManager.GetString("A038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A039 {
            get {
                return ResourceManager.GetString("A039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A040 {
            get {
                return ResourceManager.GetString("A040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A041 {
            get {
                return ResourceManager.GetString("A041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A042 {
            get {
                return ResourceManager.GetString("A042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A043 {
            get {
                return ResourceManager.GetString("A043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A044 {
            get {
                return ResourceManager.GetString("A044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A045 {
            get {
                return ResourceManager.GetString("A045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A046 {
            get {
                return ResourceManager.GetString("A046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A047 {
            get {
                return ResourceManager.GetString("A047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A048 {
            get {
                return ResourceManager.GetString("A048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A049 {
            get {
                return ResourceManager.GetString("A049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A050 {
            get {
                return ResourceManager.GetString("A050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A051 {
            get {
                return ResourceManager.GetString("A051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A052 {
            get {
                return ResourceManager.GetString("A052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A053 {
            get {
                return ResourceManager.GetString("A053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A054 {
            get {
                return ResourceManager.GetString("A054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A055 {
            get {
                return ResourceManager.GetString("A055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A056 {
            get {
                return ResourceManager.GetString("A056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A057 {
            get {
                return ResourceManager.GetString("A057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A058 {
            get {
                return ResourceManager.GetString("A058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A059 {
            get {
                return ResourceManager.GetString("A059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A060 {
            get {
                return ResourceManager.GetString("A060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string A061 {
            get {
                return ResourceManager.GetString("A061", resourceCulture);
            }
        }
    }
}
